# -*- coding: utf-8 -*-
"""Number-Pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JeB53lNq453Pvu1EGTRpqZc_1x4LxW2I
"""

#increasing triangle with all one
n=5
for i in range(n):
  for j in range(i+1):
    print('1',end=' ')
  print()

#increasing triangle with increasing number
p=1
for i in range(n):
  for j in range(i+1):
    print(p,end=' ')
  p+=1
  print()

#increasing triangle with decreasing pattern
p=5
for i in range(n):
  for j in range(i+1):
    print(p,end=' ')
  p-=1
  print()

#printing even number
p=0
for i in range(n):
  for j in range(i+1):
    print(p,end=' ')
  p+=2
  print()

#printing alternate number
for i in range(n):
  for j in range(i+1):
    if(i%2==0):
      print('1',end=' ')
    else:
      print('2',end=' ')
  print()

#diamond pattern
for i in range(n-1):
  p=1
  for j in range(i,n):
    print(' ',end=' ')
  for j in range(i):
    print(p,end=' ')
    p+=1
  for j in range(i+1):
    print(p,end=' ')
    p+=1
  print()
for i in range(n):
  p=1
  for j in range(i+1):
    print(' ',end=' ')
  for j in range(i,n-1):
    print(p,end=' ')
    p+=1
  for j in range(i,n):
    print(p,end=' ')
    p+=1
  print()

#diamonnd pattern increasing and decreasing
p=1
for i in range(n-1):
  for j in range(i,n):
    print(' ',end=' ')
  for j in range(i):
    print(p,end=' ')
  for j in range(i+1):
    print(p,end=' ')
  p+=1
  print()
for i in range(n):
  for j in range(i+1):
    print(' ',end=' ')
  for j in range(i,n-1):
    print(p,end=' ')
  for j in range(i,n):
    print(p,end=' ')
  p-=1
  print()

#change in column number
for i in range(n):
  p=1
  for j in range(i+1):
    print(p,end=' ')
    p+=1
  print()

#decreasing triangle
for i in range(n):
  p=1
  for j in range(i+1):
    print(' ',end=' ')
  for j in range(i,n):
    print(p,end=' ')
    p+=1
  print()

#decreasing number triangle
for i in range(n):
  p=5
  for j in range(i+1):
    print(p,end=' ')
    p-=1
  print()

#decreasing triangle with decrasing column
k=5
for i in range(n):
  p=k
  for j in range(i+1):
    print(' ',end=' ')
  for j in range(i,n):
    print(p,end=' ')
    p-=1
  k-=1
  print()

#floyd triangle
k=1
for i in range(n):
  for j in range(i+1):
    print(k,end=' ')
    k+=1
  print()

#butterfly pattern
for i in range(n-1):
  p=1
  for j in range(i+1):
    print(p,end=' ')
    p+=1
  for j in range(i,n-1):
    print(' ',end=' ')
  for j in range(i,n-1):
    print(' ',end=' ')
  p=1
  for j in range(i+1):
    print(p,end=' ')
    p+=1
  print()
for i in range(n):
  p=1
  for j in range(i,n):
    print(p,end=' ')
    p+=1
  for j in range(i):
    print(' ',end=' ')
  for j in range(i):
    print(' ',end=' ')
  p=1
  for j in range(i,n):
    print(p,end=' ')
    p+=1
  print()